package com.mycompany.report_generator.services;

import com.mycompany.report_generator.models.Observation;
import com.mycompany.report_generator.models.ObservationReport;
import org.springframework.stereotype.Service;

import java.util.List;

@Service
public class LLMReportGenerationService implements ReportGenerationService {

    private final LLMClient llmClient;

    public LLMReportGenerationService(LLMClient llmClient) {
        this.llmClient = llmClient;
    }

    @Override
    public ObservationReport generateReport(Observation observation) {
        String inputPrompt = buildPromptFromObservation(observation);
        String llmOutput = llmClient.generateReport(inputPrompt);

        return ObservationReport.builder()
                .patientName(observation.getPatient() != null ?
                        observation.getPatient().getFirstName() + " " + observation.getPatient().getLastName()
                        : "Unknown Patient")
                .doctorName(observation.getDoctor() != null ?
                        observation.getDoctor().getFirstName() + " " + observation.getDoctor().getLastName()
                        : "Unknown Doctor")
                .observationSummary(observation.getSymptomsDescription())
                .potentialDiagnosis("Generated by LLM")
                .riskFactors(List.of(llmOutput))
                .build();
    }

    private String buildPromptFromObservation(Observation obs) {
        return "Generate a cardiology report for patient with vitals: " + obs.getVitalSigns()
                + " and symptoms: " + obs.getSymptomsDescription();
    }
}
